zipcode:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: zipcode
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - name: zipfs
          repo: community
      attach:
        - path: "md:zipcode"
          alias: zipcode
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: zipcode
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - name: zipfs
          repo: community
      attach:
        - path: "md:dev_zipcode"
          alias: zipcode
          is_ducklake: true
